version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - backend
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
